CREATE TABLE IF NOT EXISTS Coin (
    id      INTEGER     NOT NULL,
    value   INTEGER     NOT NULL,
    PRIMARY KEY (id)
);
CREATE SEQUENCE IF NOT EXISTS HIBERNATE_SEQUENCE START WITH 5 INCREMENT BY 1;